### ISSUE TITLE
.htacces is not supported by nginx

### ISSUE THREAD

**Issue by nerg4l** [RamesesLabs/Nginx_Config_PHP_Framework#2]
Quote from [reddit thread](https://www.reddit.com/r/PHP/comments/9fplpg/github_repo_with_nginx_server_config_files/e5ycwfl)

>> Create .htaccess file in the public folder of your project or framework.
> 
> WAT?!   
> 
> Come on, shut down this repository, it's a shame to display such a level of ignorance. 

What colshrapnel is trying to say here is that nginx does not have `.htaccess` file support.

If you want to know the reason why, here is a link from the nginx wiki: https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

**Comment by RamesesLabs** [comment]
I understand now, I'm coming from Apache, and like I said in the Reddit thread, this is week one for me with Nginx on Ubuntu. I just see a lot of people with the same problems in the places I go for researching php development. I haven't been on Ubuntu that long either. Thanks for the information and the much kinder reply then colshrapnel. I deleted the .htaccess file and I'm also going to update my notes on enabling a site.
