### ISSUE TITLE
Folder permission

### ISSUE THREAD

**Issue by nerg4l** [RamesesLabs/Nginx_Config_PHP_Framework#4]
Current readme suggests permission `757` for `/var/www`, `/var/www/your_site.com` and `/var/www/your_site.com/html` folders.

This means

- `rwx` for the owner of the file.
- `rw-` for members of the group owning the file
- `rwx` for other users

This is bad for security. You give other users permission to create new files in those folders. `755` should be enough for `php-fpm`/`nginx`.

Previously as I remember permission `775` was in the document. Try to avoid modifying the root folder permissions. Only if the framework has some kind of storage folder then permission `775` should be used for that folder only.

**Comment by RamesesLabs** [comment]
I changed the permissions to 755, I'm still new to these as well. I appreciate the help,
